version: '3.8'

services:
  backend:
    container_name: spot-app-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/spotdb
      - SPRING_DATASOURCE_USERNAME=spotuser
      - SPRING_DATASOURCE_PASSWORD=spotpass
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: spot-db
    restart: always
    environment:
      POSTGRES_DB: spotdb
      POSTGRES_USER: spotuser
      POSTGRES_PASSWORD: spotpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: