version: '3.8'

services:
  backend:
    container_name: spot-app-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    environment:
      - JWT_HS256_SECRET=BqabkJAeVi05MyT8+ByDIGEFzW8pC9+XT7eu58G4abXqt7yyygjE64OBy9SqGZPo4GAF2L+/5WUL2/YuTC677Q==
      - GOOGLE_CLIENT_ID=1011487694978-jhk1iffninu9htj5af3r3p7nrkjgmodk.apps.googleusercontent.com
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/spotdb
      - SPRING_DATASOURCE_USERNAME=spotuser
      - SPRING_DATASOURCE_PASSWORD=spotpass
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: spot-db
    restart: always
    environment:
      POSTGRES_DB: spotdb
      POSTGRES_USER: spotuser
      POSTGRES_PASSWORD: spotpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: